image: atlassian/default-image:2

pipelines:
  branches:
    main:
      - step:
          name: Build Docker Image
          runs-on:
            - self.hosted
            - linux
          services:
            - docker
          caches:
            - docker
          script:
            - echo "Building Docker Image..."
            - docker build -t pepewee/whatsapp-webhook:$VERSION -f Dockerfile .
            - docker tag pepewee/whatsapp-webhook:$VERSION pepewee/whatsapp-webhook:latest
      - step:
          name: Push Docker Image to Docker Hub
          runs-on:
            - self.hosted
            - linux
          services:
            - docker
          caches:
            - docker
          script:
            - echo "Logging in to Docker Hub..."
            - echo $DOCKER_HUB_TOKEN | docker login -u $DOCKER_HUB_USER --password-stdin
            - echo "Pushing Image..."
            - docker push pepewee/whatsapp-webhook:$VERSION
            - docker push pepewee/whatsapp-webhook:latest
      - step:
          name: Deploy to Server
          runs-on:
            - self.hosted
            - linux
          script:
            - pipe: atlassian/ssh-run:0.4.3
              variables:
                SSH_USER: "$SSH_USER"
                SERVER: "$SSH_HOST"
                SSH_KEY: "$SSH_KEY"
                COMMAND: |
                  echo "Logging into Docker Hub on remote server..."
                  echo $DOCKER_HUB_TOKEN | docker login -u $DOCKER_HUB_USER --password-stdin
                  echo "Pulling image..."
                  docker pull pepewee/whatsapp-webhook:latest
                  echo "Deploying updated containers..."
                  cd /data/sites/ia-sp-webhook.ucatolica.cue.ec/html/webhook
                  docker-compose down
                  docker-compose up -d
                  echo "Deployment complete!"
definitions:
  services:
    docker:
      memory: 2048
