services:
  whatsapp_webhook:
    container_name: catia-webhook
    image: pepewee/whatsapp-webhook:latest
    ports:
      - "8081:8080"
    env_file:
      - .env
    volumes:
      - whatsapp_webhook_logs:/app/logs
    restart: always
    networks:
      - virtual_assistant_network

volumes:
  whatsapp_webhook_logs:

networks:
  virtual_assistant_network:
    external: true